name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Get Code Climate Test Report
        env:
          CC_TEST_REPORTER_ID: 31c967e76b811073f1a8ceae857dfab681f0b153fbd56ae68760c914fff86c63
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.6.3-darwin-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          
      - name: Brew Install Xcodecoverageconverter
        run: brew install twittemb/formulae/Xcodecoverageconverter
          
      - name: Prepare Code Coverage
        run: ./cc-test-reporter before-build

      - name: Clean
        run: xcodebuild clean -scheme iNavTelemetry -project iNavTelemetry.xcodeproj
      
      - name: Build
        run: xcodebuild build-for-testing -scheme iNavTelemetry -project iNavTelemetry.xcodeproj -destination "generic/platform=iOS Simulator"
      
      - name: Test
        run: xcodebuild test -scheme iNavTelemetry -project iNavTelemetry.xcodeproj -destination "platform=iOS Simulator,name=iPhone 13" -enableCodeCoverage YES -resultBundlePath result.xcresult
       
      - name: Generate Report
        run: xcrun xccov view --report result.xcresult --json > coverage.json

      - name: Convert Report to Cobertura
        run: xcc generate coverage.json . cobertura-xml 

      - name: Upload Code Coverage
        run: ./cc-test-reporter after-build -t cobertura -r 31c967e76b811073f1a8ceae857dfab681f0b153fbd56ae68760c914fff86c63
